name: Fabric CI

on:
  push:
    branches:
      - development

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display Start Message
        run: echo "Fabric CI Pipeline Started"

      - name: Show Repository Files
        run: ls -R

      - name: Display Completion Message
        run: echo "Fabric CI Pipeline Completed Successfully"
