name: Fabric CI

on:
  push:
    branches:
      - test

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check folders
        run: |
          echo "Validating folders..."

          for folder in notebooks pipelines sql; do
            if [ ! -d "$folder" ]; then
              echo "ERROR: Missing $folder"
              exit 1
            fi
          done

          echo "All folders exist ✔"
